/root/ghc-7.8.4/inplace/lib/bin/haddock -B/root/ghc-7.8.4/inplace/lib -l/root/ghc-7.8.4/inplace/lib --odir=libraries/binary/dist-install/doc/html/binary --no-tmp-comp-dir --dump-interface=libraries/binary/dist-install/doc/html/binary/binary.haddock --html --hoogle --title=binary-0.7.1.0: Binary serialisation for Haskell values using lazy ByteStrings --prologue=libraries/binary/dist-install/haddock-prologue.txt --hide=Data.Binary.Builder.Base --hide=Data.Binary.Class --hide=Data.Binary.Generic --read-interface=../array-0.5.0.0,../array-0.5.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/array/dist-install/doc/html/array/array.haddock --read-interface=../base-4.7.0.2,../base-4.7.0.2/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../bytestring-0.10.4.0,../bytestring-0.10.4.0/src/%{MODULE/./-}.html#%{NAME},libraries/bytestring/dist-install/doc/html/bytestring/bytestring.haddock --read-interface=../containers-0.5.5.1,../containers-0.5.5.1/src/%{MODULE/./-}.html#%{NAME},libraries/containers/dist-install/doc/html/containers/containers.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=binary-0.7.1.0 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/binary/src --optghc=-ilibraries/binary/dist-install/build --optghc=-ilibraries/binary/dist-install/build/autogen --optghc=-Ilibraries/binary/dist-install/build --optghc=-Ilibraries/binary/dist-install/build/autogen --optghc=-Ilibraries/binary/. --optghc=-optP-DGENERICS --optghc=-optP-include --optghc=-optPlibraries/binary/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=array-0.5.0.0 --optghc=-package --optghc=base-4.7.0.2 --optghc=-package --optghc=bytestring-0.10.4.0 --optghc=-package --optghc=containers-0.5.5.1 --optghc=-O2 --optghc=-Wall --optghc=-fliberate-case-threshold=1000 --optghc=-XHaskell98 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/binary/dist-install/build --optghc=-hidir --optghc=libraries/binary/dist-install/build --optghc=-stubdir --optghc=libraries/binary/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/binary/src/Data/Binary.hs libraries/binary/src/Data/Binary/Put.hs libraries/binary/src/Data/Binary/Get.hs libraries/binary/src/Data/Binary/Get/Internal.hs libraries/binary/src/Data/Binary/Builder.hs libraries/binary/src/Data/Binary/Builder/Internal.hs libraries/binary/src/Data/Binary/Builder/Base.hs libraries/binary/src/Data/Binary/Class.hs libraries/binary/src/Data/Binary/Generic.hs +RTS -tlibraries/binary/dist-install/doc/html/binary/binary.haddock.t --machine-readable 
 [("bytes allocated", "699889000")
 ,("num_GCs", "916")
 ,("average_bytes_used", "20023910")
 ,("max_bytes_used", "54785888")
 ,("num_byte_usage_samples", "8")
 ,("peak_megabytes_allocated", "121")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.38")
 ,("mutator_wall_seconds", "0.51")
 ,("GC_cpu_seconds", "0.53")
 ,("GC_wall_seconds", "0.65")
 ]
