/root/ghc-7.8.4/inplace/lib/bin/haddock -B/root/ghc-7.8.4/inplace/lib -l/root/ghc-7.8.4/inplace/lib --odir=libraries/process/dist-install/doc/html/process --no-tmp-comp-dir --dump-interface=libraries/process/dist-install/doc/html/process/process.haddock --html --hoogle --title=process-1.2.0.0: Process libraries --prologue=libraries/process/dist-install/haddock-prologue.txt --read-interface=../base-4.7.0.2,../base-4.7.0.2/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../deepseq-1.3.0.2,../deepseq-1.3.0.2/src/%{MODULE/./-}.html#%{NAME},libraries/deepseq/dist-install/doc/html/deepseq/deepseq.haddock --read-interface=../directory-1.2.1.0,../directory-1.2.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/directory/dist-install/doc/html/directory/directory.haddock --read-interface=../filepath-1.3.0.2,../filepath-1.3.0.2/src/%{MODULE/./-}.html#%{NAME},libraries/filepath/dist-install/doc/html/filepath/filepath.haddock --read-interface=../unix-2.7.0.1,../unix-2.7.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/unix/dist-install/doc/html/unix/unix.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=process-1.2.0.0 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/process/. --optghc=-ilibraries/process/dist-install/build --optghc=-ilibraries/process/dist-install/build/autogen --optghc=-Ilibraries/process/dist-install/build --optghc=-Ilibraries/process/dist-install/build/autogen --optghc=-Ilibraries/process/include --optghc=-optP-include --optghc=-optPlibraries/process/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=base-4.7.0.2 --optghc=-package --optghc=deepseq-1.3.0.2 --optghc=-package --optghc=directory-1.2.1.0 --optghc=-package --optghc=filepath-1.3.0.2 --optghc=-package --optghc=unix-2.7.0.1 --optghc=-Wall --optghc=-XHaskell2010 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/process/dist-install/build --optghc=-hidir --optghc=libraries/process/dist-install/build --optghc=-stubdir --optghc=libraries/process/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/process/./System/Cmd.hs libraries/process/./System/Process.hs libraries/process/./System/Process/Internals.hs +RTS -tlibraries/process/dist-install/doc/html/process/process.haddock.t --machine-readable 
 [("bytes allocated", "488580064")
 ,("num_GCs", "550")
 ,("average_bytes_used", "13874592")
 ,("max_bytes_used", "36953192")
 ,("num_byte_usage_samples", "7")
 ,("peak_megabytes_allocated", "77")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.29")
 ,("mutator_wall_seconds", "0.32")
 ,("GC_cpu_seconds", "0.32")
 ,("GC_wall_seconds", "0.44")
 ]
